### PR TITLE
README++

### PR DESCRIPTION
**Pull request by bencevans**

### CODE REVIEW

**Comment by bencevans** [comment]
@paulbjensen could you have a quick peek, see if it make sense?

**Comment by paulbjensen** [comment]
You'll want to fix the markdown for the DavidDM badge

**Comment by paulbjensen** [comment]
I read the Readme, It makes sense. The thing I picked up was that <code>myBlackBoxVideoConverter()</code> was not defined anywhere in the example, it might be good to define it with something small and simple, just so that copy 'n pasting devs don't get confused by it.

**Comment by bencevans** [comment]
Thanks, both the changes taken on board and will push up fixes next time 
I'm working. Would you have any suggestions for an example 
`myBlackBoxVideoConverter()` that would be compatible as a duplex stream?

**Comment by bencevans** [comment]
@paulbjensen I've pushed those changes.

**Pull request merged**
